import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import { Providers } from "./chakra/provider";
import { Providers as ReduxProvider } from "@/redux/provider";
import "./index.css";

const plusJakaraSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Quick Chop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={plusJakaraSans.className}>
        <ReduxProvider>
          {" "}
          <Providers>{children}</Providers>
        </ReduxProvider>
      </body>
    </html>
  );
}
