export type UserResponse = {
  id: string;
  email: string;
  phone: string;
  disable: boolean;
  name: string;
  like: { restaurantId: string }[];
  location: any;
  dislike: { restaurantId: string }[];
  orders: [];
  loginInfo: [];
  verified: boolean;
  OTP: number;
  password: string;
  photo: string | null;
  balance: number;
  locationId: string | null;
  paymentId: string | null;
  preferencesId: string | null;
  createdAt: Date;
  updatedAt: Date;
};

export type RestaurantResponse = {
  id: string;
  name: string;
  verified: boolean;
  loadingImage: string;
  ratingAmount: string | null;
  location: any;
  menu: [];
  orders: [];
  category: { id: string; type: string }[];
  available: boolean;
  slug: string;
  photo: string;
  like: { restaurantId: string }[];
  dislike: { restaurantId: string }[];
  rating: string | null;
  createdAt: Date;
  updatedAt: Date;
  locationId: string | null;
  restaurantAdminId: string | null;
};
